[Settings]
ID = "333e15f3-f8cc-4435-815c-b93e8bcf188e"

[build.environment]
TZ='Asia/Jakarta'

[[headers]]
  for = "/*"
  [headers.values]
    cache-control: max-age=0,no-cache,no-store,must-revalidate
    #Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# [[plugins]]
# package = "netlify-plugin-checklinks"

# [[plugins]]
# package = "netlify-plugin-image-optim"